name: 'dns_cf_push'

on:
  schedule:    # 保留原有定时任务
    - cron: '0 */6 * * *'
  workflow_dispatch:   # 新增手动触发选项
    inputs:
      description: 
        description: '手动触发说明（可选）'
        required: false
        default: '手动执行 DNS 更新'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Set up Python'
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: 'Install dependencies'
        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: 'run dnscf'
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CF_DNS_NAME: ${{ secrets.CF_DNS_NAME }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        run: python dnscf.py
